### ISSUE TITLE
RMI serialization problem

### ISSUE THREAD

**Issue by bolbat** [anotheria/moskito#100]
Hello, please fix the next issue:

- net.anotheria.moskito.core.config.journey.JourneyConfig should be Serializable
- also review other classes included in RMI API for working serialization

**Exception stack trace:**
Service unavailable due to rmi failure: error unmarshalling return; nested exception is: java.io.WriteAbortedException: writing aborted; java.io.NotSerializableException: net.anotheria.moskito.core.config.journey.JourneyConfig

[net.anotheria.moskito.webui.shared.api.generated.RemoteAdditionalFunctionalityAPIStub.mapException(RemoteAdditionalFunctionalityAPIStub.java:1525), net.anotheria.moskito.webui.shared.api.generated.RemoteAdditionalFunctionalityAPIStub.getConfiguration(RemoteAdditionalFunctionalityAPIStub.java:1180), net.anotheria.moskito.webui.shared.api.generated.RemoteAdditionalFunctionalityAPIStub.getConfiguration(RemoteAdditionalFunctionalityAPIStub.java:1171), net.anotheria.moskito.webui.shared.api.generated.RemoteAdditionalFunctionalityAPIStub.getConfiguration(RemoteAdditionalFunctionalityAPIStub.java:1047), net.anotheria.moskito.webui.accumulators.action.ShowAccumulatorsAction.execute(ShowAccumulatorsAction.java:84), net.anotheria.maf.MAFFilter.doPerform(MAFFilter.java:274), net.anotheria.maf.MAFFilter.doFilter(MAFFilter.java:215), org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240), org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207), org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212), org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106), org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502), org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141), org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79), org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88), org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528), org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1099), org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672), org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520), org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617), org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61), java.lang.Thread.run(Thread.java:745)]

**Comment by bolbat** [comment]
We are waiting for next minor release with this fix

**Comment by dvayanu** [comment]
cross reference: https://jira.opensource.anotheria.net/browse/MSK-375

**Comment by dvayanu** [comment]
2.7.5 is sent to central.
