### ISSUE TITLE
Make "Olark" JS disable/enable via configuration (like trackUsage pixel)

### ISSUE THREAD

**Issue by bolbat** [anotheria/moskito#103]
Currently moskito-inspect web ui works much more slowly due to Olark plugin.
And have external resources from Olark domain.
I purpose to make it optional (disable flag in moskito-inspect.json) like trackUsage (pixel) functionality.

**Comment by dvayanu** [comment]
fixed in MSK-377, 2.7.6-SNAPSHOT - https://jira.opensource.anotheria.net/browse/MSK-377
