### ISSUE TITLE
Autoreload feature on moskito-inpect web ui

### ISSUE THREAD

**Issue by bolbat** [anotheria/moskito#104]
After update to 2.7.x (from 2.4.x) version we doesn't see autoreload feature.
They are very useful for us for accumulators page. 

In sources (Header.jsp) i see the next comment: <%-- removing autoreload feature for now, we can readd it later --%>

When we can see it back?

**Comment by dvayanu** [comment]
This feature wasn't re-added after migration to new ui (inspect) and honestly you are the first to ask ;-)
I think the autoreload feature should be added for dashboards, but we don't have concrete plans for a date yet. 
But feel free to submit a patch ;-)

**Comment by bolbat** [comment]
I will think about pull request, but doesn't have enough skills to make UI part perfect.

**Comment by dvayanu** [comment]
The issue is now on the roadmap https://jira.opensource.anotheria.net/browse/MSK-392

**Comment by dvayanu** [comment]
Fixed with 2.7.6
