### ISSUE TITLE
RMI API improvement to have backward compatibility with previous versions

### ISSUE THREAD

**Issue by bolbat** [anotheria/moskito#105]
Currently most Serializable classes participated in RMI API doesn't have serialVersionUID field.
This mean Java serialization calculate it dynamically at runtime by class structure (see java.io.ObjectStreamClass.computeDefaultSUID(Class<?>) for details).

And because of this - any minor change in any Serializable class participated in RMI API break compatibility with previous versions.
For example this problem exists between 2.7.4 and 2.7.5 versions.

I purpose to generate some constant serialVersionUID to all Serializable classes in moskito (not only in RMI API to be sure in future iterations).

And implement writeObject/readObject/readResolve in classes where this needed (frequently changing classes) to have agile mechanism for backward compatibility.

**Comment by dvayanu** [comment]
yes, thank you. we will generate serialversionuids in all serializeable classes.

**Comment by dvayanu** [comment]
fixed in https://github.com/anotheria/moskito/commit/3fc5b6471121294da28a0a662b545b9e4600e603
