### ISSUE TITLE
Missing StatValues (Used instead Free)

### ISSUE THREAD

**Issue by marlonpatrick10** [anotheria/moskito#121]
Hello everyone.

I am studying and doing some tests with Moskito to deploy in my company. I do not have much experience with the tool and I have a simple question.

When trying to create some Gauges I missed some StatsValues ​​which I find simple to add. For example, OSStats does NOT have the amount of memory in use. Although this information does not exist directly in MXBean, but if you have Total and Free, then you also have how much was used.

In my opinion this is quite useful for creating Gauges, for me it is not natural to have a Gauge that measures free memory, in fact I need to measure the memory in use.

I noticed something similar also in DiscSpaceProducer.

Is there any special reason not to create StatValues ​​like these?

Another thing, still about BuiltInOSProducer, is there any special reason not to get interesting stats like Swap and Load Average?

I'm thinking of creating a "CustomOSProducer" that would add some information like these. Is there any contraindication?

Thank you!

**Comment by dvayanu** [comment]
Hi Marlon,
actually there are no contradictions and the values you are mentioned seems very useful.
As for used memory this is indeed easy to add as calculated value. If you want to test yourself, feel free to open a pull request ;-)
As for Swap and LoadAverage, I am not sure, whether they are supported by the standard implementations of the MxBean on all platforms, or only by com.sun.management.OperatingSystemMXBean? 
If you think we can add them to the standard BuiltinOSProducer impl without breaking compatibility for windows and macos users, go for a pull request, it will be thankfully reviewed and accepted.

regards
Leon

**Comment by marlonpatrick10** [comment]
Ok Leon, thank you.

I will do this, a pull request.

About Swap and LoadAverage, yes, both are available in OperatingSystemMXBean.
