### ISSUE TITLE
Override url-pattern from GenericMonitoringFilter 

### ISSUE THREAD

**Issue by marlonpatrick10** [anotheria/moskito#122]
Hello,

I wonder if there is any way to filter the URLs (url-pattern) that GenericMonitoringFilter should observe through some configuration on moskiton.json or similar?

Otherwise I understand that the best way to do this is to simply override the Filter statement in my web.xml. Any caveats on that?

Just to be clearer, basically I want to monitor only the URLs of my main pages, without worrying about static resources like css, js and others.

PS: Is there any other channel that is more suitable for this type of doubt?

**Comment by dvayanu** [comment]
HI Marlon,
the channel is ok, whatever serves you most. We have had a mailing list once but we have currently none. Somehow mailing lists seems to be something very 2000ish. 

As for the request, I think what you want is something similar to net.anotheria.moskito.web.filters.RequestURIFilter
The RequestURIFilter itself is deprecated, cause we moved the functionality into the  GenericMonitoringFilter, but for your use-case it would be probably easiest to create your own filter similar to the RequestURIFilter and decide in the extractCaseName method which URI to monitor separately and which to put together under 'CSS' or 'IMAGES'

Does it help?
Leon

**Comment by marlonpatrick10** [comment]
Ok, Leon.

Thank you.
