### ISSUE TITLE
Remove specific producers

### ISSUE THREAD

**Issue by marlonpatrick10** [anotheria/moskito#123]
Hi, 

Can I remove some producers through moskito.json? Do not just filter, but unregister so that they do not generate statistics.

If no, what the best way to do this?

I thought about creating a plugin that does this job right at startup and also then registers a listener that to unregister producers just when they are registered.

To be more specific I want to unregister all the producers of category/subsystem: api/default and storage/default. Can I do it without major problems or does the Moskito need it internally?

**Comment by marlonpatrick10** [comment]
Ow, a suggestion: instead of loading multiple producers automatically, I suggest that they need to be explicitly registered, just like the plugins.

**Comment by dvayanu** [comment]
Hi Marlon,
question: do you want the providers to disappear or do you want them to be offloaded?

Besides you have multiple options now:
a) The Builtin Producers can be switched off via moskito.json: https://confluence.opensource.anotheria.net/display/MSK/MoSKito-Essential+Configuration+Guide#MoSKito-EssentialConfigurationGuide-BuiltinProducers

 
"@builtinProducersConfig": {
    "javaMemoryProducers": false,
    "javaMemoryPoolProducers": false,
    "osProducer": false
}

b) in the moskito-inspect (the user interface) you can configure produce filter in the file called moskito-inspect.json
example:
    "@filters": [
        /*
            This producer would filter anything by name, for example *API, *FOO* or Simple ThresholdAPI.
            Similar producers are net.anotheria.moskito.webui.producers.api.filters.ProducerCategoryFilter and
            net.anotheria.moskito.webui.producers.api.filters.ProducerSubsystemFilter
        {
            "clazzName": "net.anotheria.moskito.webui.producers.api.filters.ProducerIdFilter",
            "parameter": "ThresholdAPI"
        },*/
        {
            //this producer filter will remove internal APIs from the producer list.
            //remove it if you want to use it
            "clazzName": "net.anotheria.moskito.webui.producers.api.filters.InternalProducerFilter",
            "parameter": "none"
        }
    ],

**Comment by marlonpatrick10** [comment]
Leon, I want unregister cetains producers (storage, api).

I do this:

![image](https://cloud.githubusercontent.com/assets/1513408/23214140/5f552a30-f8ec-11e6-80a6-285aafd5fb2c.png)

What do you think? In the Moskito universe is this an acceptable strategy ??
Are you having trouble removing these producers?

**Comment by dvayanu** [comment]
Yes, I think this will not break anything. What is your intention? Remove unneeded stuff from Inspect?

**Comment by marlonpatrick10** [comment]
Ok Leon.

Yes, my intention is remove unneeded statistics. 

I did something similar also for some standard Accumulators, I want to leave only what I will really analyze.

Thank you!
