### ISSUE TITLE
Gauge with decimal values

### ISSUE THREAD

**Issue by marlonpatrick10** [anotheria/moskito#125]
Hi,

I'm trying to create Gauges from some statistics that return Double values (ex: RequestOrientedStats.errorRate).

When you do this, an error occurs in the net.anotheria.moskito.webui.gauges.api.GaugeAPIImpl class because it attempts to convert the values to long.

For now, my solution was to overwrite the class and handle Double values. Apparently it worked without problems, I did not have to adjust anywhere else.

![image](https://cloud.githubusercontent.com/assets/1513408/23284463/776d7d42-fa0a-11e6-9826-401ea5d875ba.png)

**Comment by dvayanu** [comment]
would you like to provide a pull request?

**Comment by marlonpatrick10** [comment]
Leon, any specific rules for sending a pull request? Should I do this from the master branch?

**Comment by dvayanu** [comment]
you should create your own fork, make the change there, test it, than create a pull request from master to master.

**Comment by dvayanu** [comment]
added to 2.7.8 - https://confluence.opensource.anotheria.net/display/MSK/Change+Log
