### ISSUE TITLE
Make default Accumulators and Thresholds optional

### ISSUE THREAD

**Issue by marlonpatrick** [anotheria/moskito#127]
Although good examples I suggest making Accumulators and Thresholds optional.

That's because many of these default settings may not be needed by the end user and may end up consuming more memory / processing than necessary.

Generally speaking I suggest that Moskito create its own mechanisms to initialize "stuff" and DO NOT use events from other api like Servlet (listeners).

That way, I suggest that standard Accumulators and Thresholds be loaded via plugins instead of ServletContextListener. With this, they will be easily configurable through moskito.json. In addition, the default moskito-inspect distribution can already declare these plugins so that users can evaluate whether they are useful or not.

**Comment by dvayanu** [comment]
This is actually a very good idea, thank you.

**Comment by dvayanu** [comment]
Thinking more about that, they can actually be created in the *moskito.json*, without additional code like listeners.
So once you have the demo installation, you have them all, and if you don't need them, you simply remove it from moskito.json.

**Comment by dvayanu** [comment]
@marlonpatrick10 what do you think?
Also @michaelschuetz @StetsiukRoman @sshscp @aosadchy @Bezuhlyi - like it or not?

**Comment by Bezuhlyi** [comment]
I've got no reason why not. As I see too, this is what is already happening in "@accumulatorsConfig" here [_moskito-inspect-standalone/moskito.json_](https://github.com/anotheria/moskito/blob/4ab5d5f4e9f0c8e2025b8975e6b2de960ef373bc/moskito-inspect-standalone/src/main/resources/moskito.json), the same is possible for "@thresholdsConfig" as I see.

However, the underlying built-in producers are still registered and operating. But if the one wants it can be easily changed through the same _moskito.json_:
https://github.com/anotheria/moskito/blob/df68e3c8e675c527fac6d01570291452c03716e6/moskito-core/src/main/java/net/anotheria/moskito/core/util/StartBuiltInProducers.java

When going this way at least two classes look like no longer needed:
- https://github.com/anotheria/moskito/blob/df68e3c8e675c527fac6d01570291452c03716e6/moskito-webui/src/main/java/net/anotheria/moskito/webui/util/SetupPreconfiguredAccumulators.java
- https://github.com/anotheria/moskito/blob/master/moskito-inspect-standalone/src/main/java/net/anotheria/moskitominimal/listeners/SetupThresholds.java

And where (which project) do we need to put _moskito.json_ with a configured showcases for built-in accumulators and thresholds, so the user who integrates MoSKito into one's own application has that accumulators and thresholds running?

**Comment by dvayanu** [comment]
@Bezuhlyi I assume this one: https://github.com/anotheria/moskito/blob/master/moskito-inspect-standalone/src/main/resources/moskito.json

**Comment by dvayanu** [comment]
@Bezuhlyi But I also think we should use *include* feature of ConfigureMe and extract predefined accumulators/thresholds into own files, this way, the user can use his own configuration and the standard ones, in case the later are changing (like now)

**Comment by Bezuhlyi** [comment]
@dvayanu It could be the most obvious way on the code level to show that something new of predefined stuff was added, a user should look into the recent _predefined-thresholds/accumulators.json_ in the repository then. But I'm not sure either this is or there is another strong reason to have predefined thresholds and accumulators exactly as a unitary section.

However, different included accumulators/threshold sets config files (and maybe not only for the built-in ones) can be used for different stages (environments) without creating a full description mess in the main config file.

**Comment by marlonpatrick10** [comment]
@dvayanu, , about move default Accumulators and Thresholds from listeners to moskito.json I think that's great. That way, I as a user can configure without having to change code.

**Comment by dvayanu** [comment]
2.7.9 (or 2.8.0) we moved autocreation of memory and cg accumulators in the correspondign builtin producers. So if 'you' don't want to have those accumulators anymore, simply disable producers.
We will remove other auto-configured accumulators/thresholds as well

**Comment by dvayanu** [comment]
2.8.1-SNAPSHOT - Thread-related accumulators have been moved to config
