### ISSUE TITLE
Detailed Stats with out of the box Min, Max, Avg, Count, Sum.

### ISSUE THREAD

**Issue by marlonpatrick10** [anotheria/moskito#129]
Hi Leon,

I've implemented a utility class for the Moskito and want to know if it's of interest to put it in the moskito-core code. If you agree, I'll send a pull request.

Basically it is a Stats object that has in it other stats that automatically calculate the values: min, max, avg, count, sum.

In this way, if you want to implement a Producer that generates this information, instead of creating a Stats for each information, you could have in just 1 Stats all this data.

**Without DetailedStats:**

![image](https://cloud.githubusercontent.com/assets/1513408/23520918/9deb1adc-ff5b-11e6-825a-0f7451809d87.png)

**With DetailedStats:**

![image](https://cloud.githubusercontent.com/assets/1513408/23520519/1e998f4e-ff5a-11e6-91f7-b535797c4487.png)

**Comment by dvayanu** [comment]
Yes, please open a PullRequest. I understand this is something similar to RequestOrientedStats. I am not quite sure if the name 'Detailed' is a good one, cause personally I don't think its catchy.
But open a pull request and we can continue discussion in the pull request.
