### ISSUE TITLE
 MoSKito APM agent monitor TIBCO BW

### ISSUE THREAD

**Issue by prashantnitt07** [anotheria/moskito#164]
hi,
can be deploy  MoSKito agent on TIBCO BW . please check and reply ,

We have four type to JAVA based ..

Tomcat
Weblogic
Jboss
TIBCO BW
please reply all 4 java type supported  MoSKito .

**Comment by prashantnitt07** [comment]
please reply , this is urgent

**Comment by prashantnitt07** [comment]
what is step of install MoSKito APM agent on Linux Machine .
please sent guide or step for installed on Linux Machine .

**Comment by prashantnitt07** [comment]
waiting your reply

**Comment by dvayanu** [comment]
Hi, 
first of all github is not our rimary support forum, if you need fast reply please send your inquiry to support@moskito.org
Technically all containers/servers you stated will run with moskito, question is rather the java version.
1) What java version are you using for all your components?
2) Do you have access to source code, or with other words do you want to use source code instrumentation (compile time) or javaagent style approach?

regards
leon

**Comment by dvayanu** [comment]
I assume the issue can be closed, feel free to reopen if you need any help
