### ISSUE TITLE
Gauges should keep last values

### ISSUE THREAD

**Issue by dvayanu** [anotheria/moskito#217]
Gauges defined for derived values (like average will have no value if there is no recorded request in next interval. While this is technically correct, it may be a little misleading. Instead we could show the last value.
Example 
![gaugenotready](https://user-images.githubusercontent.com/2864497/49341509-999ec000-f64e-11e8-837c-8aa7ed091a1c.png)

This issue was raised in moskito-support channel.

**Comment by maxdatapt** [comment]
> Proposed solution, keep previous value in cache, if new value is an illegal one, like NaN, use the previously legal value.
> Possible inclusion 2.8.10.

Solution tested OK

**Comment by dvayanu** [comment]
Release in 2.9.0
