### ISSUE TITLE
Moskito (moskito-aop) should not instrument Java8 Lambdas as Producer

### ISSUE THREAD

**Issue by FelixJongleur42** [anotheria/moskito#219]
Just noticed that moskito-aop instruments lambdas as Producers.
Is there a proper way to avoid this?

1. They cannot be excluded via @DontMonitor (as far as I can tell)
2. They are not very well named as a Producer, e.g. "lambda$1"
3. They are potentially slow (e.g. using lamdbas for filtering large collections)
4. Using "workarounds" such as refactoring into methods with @DontMonitor don't seem to be very practical.

**Comment by dvayanu** [comment]
@ibogatyrchuk can you take a look please, what can be done?

**Comment by dvayanu** [comment]
@FelixJongleur42  Do you have any working examples?

**Comment by maxdatapt** [comment]
we were having the same issue but with the methods generated by switch cases,,, for a temporary fix we hammered down the following to the first line of MonitoringBaseAspect.doProfiling():
```
// ignore generated methods
if (getMethodStatName(pjp.getSignature()).contains("$")) {
    return pjp.proceed();
}
```

**Comment by dvayanu** [comment]
@maxdatapt @FelixJongleur42 I just added this line to skip pointcut monitoring for synthetics, its published as 2.9.2-SNAPSHOT (in couple of minutes), could you retest if this fixed the problem?

**Comment by dvayanu** [comment]
this line from above comment is
```

if (((MethodSignature)pjp.getSignature()).getMethod().isSynthetic())
			return pjp.proceed();
```

**Comment by dvayanu** [comment]
I tested the fix with following code:
```
	static enum dummyEnum {
		FIRST, SECOND;
	}


public Order placeOrder(String customerId, String... items) {
		int a = 0;
		dummyEnum dummy = customerId.length()>5 ?
				dummyEnum.FIRST : dummyEnum.SECOND;

		switch(dummy){
			case FIRST:
				a+=10;
				break;
			case SECOND:
				a-=5;
				break;
		}
```
It works, compare the screenshots for 2.9.1 and 2.9.2 (with fix)
![2 9 1](https://user-images.githubusercontent.com/2864497/54220722-5330eb00-44f2-11e9-8238-5c3dfe8c2049.png)
![2 9 2](https://user-images.githubusercontent.com/2864497/54220723-5330eb00-44f2-11e9-80e9-5ecda8802192.png)

**Comment by FelixJongleur42** [comment]
Sorry I  won’t be able to retest that quickly since we would need to to a bigger Moskito upgrade and there are too many transitive dependency changes we cannot handle right now. But your test looks good so far. 
Maybe you could add some code like Arrays.stream(dummyEnum.values()).forEach(System.out::println) (written from the head) to provoke more synthetic code for your before and after tests. thank you!

**Comment by dvayanu** [comment]
Tested with:
```
		Arrays.stream(dummyEnum.values()).forEach(dummyEnum -> {
			System.out.println(dummyEnum);
		});
````
on 2.9.1 you see a producer lambda$0
![Screenshot 2019-03-14 at 23 12 57](https://user-images.githubusercontent.com/2864497/54395078-06464380-46af-11e9-8482-77a6aaa52292.png)

On 2.9.2 (SNAPSHOT) no such producer is generated. Considering it fixed in 2.9.2

**Comment by in-fke** [comment]
After four years we finally came to upgrade, thanks for fixing this!

**Comment by dvayanu** [comment]
You are welcome, mind to share some details, on how you are using the project?

**Comment by in-fke** [comment]
> You are welcome, mind to share some details, on how you are using the project?

I'll get in touch with you via email.
