### ISSUE TITLE
BuiltinProducersConfig: disabling of errorProducer not working

### ISSUE THREAD

**Issue by maxdatapt** [anotheria/moskito#224]
BuiltinProducersConfig have a flag to disable multiple producers, every one of them works except the "errorProducer" (I am still receiving errorProducer on the moskito-central with this config:)

![image](https://user-images.githubusercontent.com/25607934/54286230-5502b900-459b-11e9-8cfa-5b41d1b9700d.png)

**Comment by dvayanu** [comment]
Are those values empty or do they contain anything?

**Comment by dvayanu** [comment]
fixed in current 2.9.2 snapshot
