### ISSUE TITLE
Tracers added via moskito.json are not enabled

### ISSUE THREAD

**Issue by Roman12761** [anotheria/moskito#235]
We can add tracers for certain producers via moskito.json, after this action tracers are held in the configuration class, but they are not enabled (they are not added to the net.anotheria.moskito.core.tracer.TracerRepository#tracers map)

Steps to reproduce: 
1. Preconfigure tracers for predefined producers in the moskito.json 
`"@tracingConfig": {
    "tracingEnabled": true,
    "loggingEnabled": true,
    "inspectEnabled": true,
    "maxTraces": 1000,
    "tracers": ["MyProducerId"],
  },`
2. Start the application and open moskito inspect ui
3. Open Tracers tab

Actual result:
Defined tracer is not present in the list of tracers, 

Expected Result: 
Tracer in the tracers list, the producer is tracked.

Version: 2.9.3

**Comment by dvayanu** [comment]
Hi @Roman12761 is 'MyProducerId' a full producer name? Like a.b.c.MyProducerId or just MyProducerId?

**Comment by Roman12761** [comment]
@dvayanu MyPoducerId is just an example of the full producer name (id).

**Comment by dvayanu** [comment]
Never mind last comment, i was able to reproduce it with moskito-demo example.

**Comment by Roman12761** [comment]
Thanks, I have a workaround, maybe it will help people until it is fixed.

**Comment by dvayanu** [comment]
Yeah I noticed that this part of the config wasn't read.

**Comment by dvayanu** [comment]
Fixed in 2.10.x, not released yet.

**Comment by dvayanu** [comment]
2.10 has been released today, the fix is part of 2.10.x release.
