### ISSUE TITLE
moskito-webui should not depend on "Dozer" which has not been updated since 2014

### ISSUE THREAD

**Issue by in-fke** [anotheria/moskito#266]
1. moskito-core excludes transitive dependency "dozer" from "ano-util" ("ano-util" no longer seems to depend on it since 2.2.0)
2. but then again, moskito-webui explicitly depends on "dozer" which has not been updated since 2014

see https://dozer.sourceforge.net/
see https://mvnrepository.com/artifact/net.sf.dozer/dozer

Could not find any explicit reference to "dozer" in moskito-webui, only here:
https://github.com/anotheria/moskito/blob/develop/moskito-webui/src/main/wireframes/else_mbeans.html

**Comment by dvayanu** [comment]
I think we removed dozer support from all libs last year, it was moved to auto-populate beans. I will try to build a dozer-free version of moskito-webui.

**Comment by dvayanu** [comment]
Yes, we released a new version of ano-maf (our struts1 replica) without auto-population beans. we will release a new version without dozer dependency, it is not needed currently anyway.

**Comment by dvayanu** [comment]
Removed dozer dependency in version 3.2.4
