### ISSUE TITLE
Error with try get MBeans

### ISSUE THREAD

**Issue by fdefigueiredo-technisys** [anotheria/moskito#73]
Hi, i get error in moskito-inspect-standalone-2.6.1 (ui) when click on Everythink Else - MBeans  get this error.

https://gist.github.com/f57b21f4eed5a6759a06

Any idea why get this error?
Thanks alot,
Diego

**Comment by dvayanu** [comment]
Hi Diego,
do you get this error only in logs or also something in the frontend? What jdk version do you use? Out of the blue I'd say you are using some 'strange' mbeans, maybe some specific mbeans that do not support get operations...

**Comment by fdefigueiredo-technisys** [comment]
Hi, thanks for your answer, i´m using JDK7 (Oracle) and this error get with and without anotations. Once it worked, but then stopped working.

**Comment by fdefigueiredo-technisys** [comment]
Hi, in my application console get this trace when try view MBeans Option into Moskito Standalone https://gist.github.com/fdefigueiredo-technisys/b2031c8e1823a1a3286c
And in Moskito standalone view this error https://gist.github.com/fdefigueiredo-technisys/934e23a061779c993595

Thanks alot,
Diego
