### ISSUE TITLE
Cannot find resources moskito Embed in my app

### ISSUE THREAD

**Issue by fdefigueiredo-technisys** [anotheria/moskito#75]
Hi, i try put moskito in my app, but i can´t entry to mui. First when try get http://mihost:port/mui get error cannot find resource /myapp/net/anotheria/moskito/webui/jsp/Producers.jsp when read this information (https://confluence.opensource.anotheria.net/display/MSK/Embedding+Moskito-WebUI+Into+Your+Application) " MoSKito can't find the JSPs ?" i insert this mappings into web.xml, stop tomcat, clean work and start again but now error changed, Now cannot find resource /mui or /mui/ i try with "myapp/mui/mskShowAllProducers" and error persist.

Thanks four your help,
regards,
Diego

**Comment by aosadchy** [comment]
Hi, Deigo!

Are you trying to embed MoSKito into the Spring web-app?

**Comment by fdefigueiredo-technisys** [comment]
Hi, yes, i'm try it with spring app.

**Comment by aosadchy** [comment]
Hello. 

I suggest you to use moskito-inspect-embedded to leverage pluggability via web-fragments.

I've created a quick sample for you based on example Spring app http://examples.javacodegeeks.com/enterprise-java/spring/mvc/spring-mvc-hello-world-example/

You can find the sample here: https://dl.dropboxusercontent.com/u/2174658/spring-msk-example.zip

To run app:
1. Build app: mvn clean package
2. Deploy war artifact into Tomcat (here I assume that you are deploying it to the / path).
3. To be sure that Spring is up-n-running access http://localhost:8080/helloWorld
4. Access MoSKito web-interface via http://localhost:8080/moskito-inspect/ 

I hope that helps!

**Comment by ehsansoleimani** [comment]
@aosadchy 
file doesn't exist at https://dl.dropboxusercontent.com/u/2174658/spring-msk-example.zip
