### ISSUE TITLE
BuiltInOSProducer doesn't recognize Windows OS properly

### ISSUE THREAD

**Issue by CSchulz** [anotheria/moskito#80]
It seems that the following check doesn't work properly:

```
if (version > '7'){
    isUnixOS = mxBean.getClass().getName().equals("sun.management.OperatingSystemImpl");
}else{
    isUnixOS = mxBean.getClass().getName().equals("com.sun.management.UnixOperatingSystem");
}
```

Perhaps use something like http://stackoverflow.com/questions/14288185/detecting-windows-or-linux

**Comment by dvayanu** [comment]
Yes it doesn't, but does windows have the capabilities to deliver the needed data? I mean is there an OperationSystemBean impl for windows at all ?;-)

**Comment by CSchulz** [comment]
Yeah some methods delivers stuff:

- getProcessCpuLoad
- getProcessCpuTime
- getSystemCpuLoad
- all memory functions

They are part of OperatingSystemImpl.

Could be possible that there is a need to rewrite the reflection part. Using the debugger I can access the values via mxBean. Using the reflection it doesn't work:

Class net.anotheria.moskito.core.util.BuiltInOSProducer can not access a member of class sun.management.OperatingSystemImpl with modifiers "public native"

**Comment by dvayanu** [comment]
Should be fixed with https://github.com/anotheria/moskito/pull/215 and 2.8.9
