### ISSUE TITLE
2.7.0: AccumulatorAPIImpl: java.io.NotSerializableException: java.util.ArrayList$SubList

### ISSUE THREAD

**Issue by fenders** [anotheria/moskito#92]
Hi, using MoSKito 2.7.0, I get an java.io.NotSerializableException when one of my accumulators have values > 200 entries. 
The exception is probably caused by `net.anotheria.moskito.webui.accumulators.api.AccumulatorAPIImpl.java:224 `

According to [this post](http://stackoverflow.com/questions/26568205/resolve-a-java-util-arraylistsublist-notserializable-exception), subList() returns an RandomAccessSubList, which is not serializable. 

The suggested solution is to create a new ArrayList, passing the sublist as constructor parameter.

So, instead of

`
List<AccumulatedValueAO> shorterList = new ArrayList<AccumulatedValueAO>();
shorterList.addAll(dataBeans.subList(dataBeans.size() - maxValues, dataBeans.size()));
dataBeans = shorterList;
`

you could try 

`List<AccumulatedValueAO> shorterList = new ArrayList<AccumulatedValueAO>(dataBeans.subList(dataBeans.size() - maxValues, dataBeans.size()));`
`dataBeans = shorterList;`

All the best
Frank

**Comment by dvayanu** [comment]
Hi Frank,

I assume it is the same issue as this one: https://jira.opensource.anotheria.net/browse/MSK-352
do you agree?

regards
Leon

**Comment by fenders** [comment]
Hi Leon,

yes, that's the same issue. I did not have an account for the anotheria jira, yet. Just created one.

Thanks.
Frank

**Comment by dvayanu** [comment]
fixed in 2.7.1 (upcoming release)
